apiVersion: v1
kind: Service
metadata:
  labels:
    app: csi
    role: controller
  name: csi-driver-controller
  namespace: {{ .Release.Namespace }}
spec:
  ports:
    - name: openstack-csi-provisioner-metrics
      port: 8080
      protocol: TCP
      targetPort: 8080
    - name: openstack-csi-attacher-metrics
      port: 8081
      protocol: TCP
      targetPort: 8081
  selector:
    app: csi
    role: controller
  type: ClusterIP
---
