{{- if .Values.kubeconfig }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "fullname" . }}-kubeconfig
  namespace: "{{ .Release.Namespace }}"
  labels:
    {{ include "labels" . | nindent 4 }}
type: Opaque
data:
  kubeconfig: {{ .Values.kubeconfig | b64enc }}
{{- end }}
