apiVersion: v1
description: A Helm chart to deploy the admission-stackit-virtual-garden application related resources
name: admission-stackit-virtual-garden
version: 0.1.0
sources:
  - https://github.com/stackitcloud/gardener-extension-provider-stackit
