{{ if (include "runtimeCluster.enabled" .) }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "name" . }}-runtime
  labels:
    {{- include "labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "name" . }}-runtime
subjects:
- kind: ServiceAccount
  name: {{ include "name" . }}
  namespace: {{ .Release.Namespace }}
{{- end }}
