{{- if .Values.config.stackitAPIEndpoints.caBundle }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "name" . }}-ca
  namespace: {{ .Release.Namespace }}
data:
  customca.crt: {{ .Values.config.stackitAPIEndpoints.caBundle }}
{{- end }}
