apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.prefix }}-cloud-provider-config
  namespace: {{ .Release.Namespace }}
data:
  cloud.yaml: |-
    global:
      projectId: "{{ .Values.projectID }}"
      iaasApi: "{{ .Values.stackitEndpoints.iaasUrl }}"
    blockStorage:
      rescanOnResize: true
