apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{.Values.prefix}}-csi-snapshot-controller
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{.Values.prefix}}-csi-snapshot-controller
    role: controller
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: {{.Values.prefix}}-csi-snapshot-controller
      role: controller
  unhealthyPodEvictionPolicy: AlwaysAllow
