---
apiVersion: autoscaling.k8s.io/v1
kind: VerticalPodAutoscaler
metadata:
  name: {{.Values.prefix}}-csi-snapshot-controller-vpa
  namespace: {{ .Release.Namespace }}
spec:
  resourcePolicy:
    containerPolicies:
    - containerName: csi-snapshot-controller
      controlledValues: RequestsOnly
  targetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{.Values.prefix}}-csi-snapshot-controller
  updatePolicy:
    updateMode: Auto
