---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.prefix }}:csi-resizer
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.prefix }}:csi-resizer
subjects:
- kind: ServiceAccount
  name: csi-resizer
  namespace: kube-system
