---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ .Values.prefix }}:csi-snapshot-controller
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Values.prefix }}:csi-snapshot-controller
subjects:
- kind: ServiceAccount
  name: csi-snapshot-controller
  namespace: kube-system
