apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.prefix }}-cloud-provider-config
  namespace: kube-system
data:
  cloud.yaml: |-
    blockStorage:
      rescanOnResize: {{ .Values.rescanBlockStorageOnResize }}
