apiVersion: v1
appVersion: "1.0"
description: A Helm chart for the Gardener STACKIT Provider extension
name: gardener-extension-provider-stackit
version: 0.1.0
sources:
  - https://github.com/stackitcloud/gardener-extension-provider-stackit
