dependencies:
- name: cloud-controller-manager
  repository: http://localhost:10191
  version: 0.1.0
  condition: cloud-controller-manager.enabled
- name: stackit-cloud-controller-manager
  repository: http://localhost:10191
  version: 0.1.0
  condition: stackit-cloud-controller-manager.enabled
- name: csi-driver-node
  repository: http://localhost:10191
  version: 0.1.0
  condition: csi-driver-node.enabled
- name: stackit-blockstorage-csi-driver
  repository: http://localhost:10191
  version: 0.1.0
  condition: stackit-blockstorage-csi-driver.enabled
