stackitOnly: false
# [Global]
authUrl: fooURL
domainName: fooDomain
tenantName: fooTenant
username: barUser
password: barPass
# applicationCredentialID: barID
# applicationCredentialName: barName
# applicationCredentialSecret: barSecret
# caCert: ""
insecure: false
region: eu
# [Networking]
# routerID: 25611bee-3143-4e81-be81-2d867fcd909f
# internalNetworkName: shoot--my-project--my-cluster
# [BlockStorage]
rescanBlockStorageOnResize: false
ignoreVolumeAZ: false
# nodeVolumeAttachLimit: 25
# [Metadata]
# requestTimeout: 1m

monitorDelay: 20s
monitorMaxRetries: 2
monitorTimeout: 30s
