{{- if and .Values.gardener.virtualCluster.enabled ( not .Values.gardener.virtualCluster.serviceAccount.name ) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{ include "labels" . | nindent 4 }}
{{- end }}
