apiVersion: v1
description: A Helm chart to deploy the admission-stackit-runtime related resources
name: admission-stackit-runtime
version: 0.1.0
sources:
  - https://github.com/stackitcloud/gardener-extension-provider-stackit
